[package]
name = "boxblocksd"
version = "0.0.1"
edition = "2021"
description = "WIP daemon for VPN proxy based on Wireguard mesh routing"
license = "MIT"
authors = ["Sol Midnight <sol@synthesis.game>"]

[[bin]]
name = "boxblocksd"
path = "src/main.rs"

[dependencies]
span = "0.2.0" 