[workspace]
members = [ "src/synthesis", "src/backend", "src/span", "src/major", "src/steam", "src/boxblox", "src/boxwarden", "src/span-macro", "src/opcode", "src/opcode-registry", "src/opcode-macro"]

resolver = "2"

[profile.release]
panic = 'abort'

[profile.dev]
panic = 'abort'
