[package]
name = "bind"
version = "0.1.0"
edition = "2024"

[dependencies]
docker = { path = "../docker"}
serde = { version = "*", features = ["derive"]}
serde_json = "1.0.140"
gemini = { path = "../gemini" }
regex = "*"

