toml[package]
name = "tailgate"
version = "0.1.0"
edition = "2021"
description = "HTTP proxy with Tailscale routing"
license = "MIT"
repository = "https://github.com/angeliteai/angelite"

[[bin]]
name = "tailgate"
path = "src/main.rs"
