[package]
name = "span"
version = "0.1.0"
edition = "2024"

[dependencies]
hyper = { version = "*", features = ["full"] }
tokio = { version = "*", features = ["full"] }
pin-project = "*"
derive_more = { version = "*" , features=["full"]}
tower = "*"
anyhow = "*"
http = "*"
