[package]
name = "span"
version = "0.2.0"
edition = "2024"
description = "Raft consensus library"
license = "MIT"

[dependencies]
thiserror = "2.0.12"
bimap = "0.6.3"
span-macro = { path = "../span-macro" }

[features]
default = ["compact"]
compact = []