[package]
name = "span"
version = "0.2.0"
edition = "2024"
description = "Raft consensus library"
license = "MIT"

[dependencies]
serde = { version = "1.0.219", features = ["derive"]}
thiserror = "2.0.12"
bimap = "0.6.3"