[package]
name = "ecs-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
itertools = "0.14.0"
quote = "1.0.38"
syn = { version = "2.0.96", features = ["full"] }
proc-macro2 = "1.0.38"
paste = "*"
