[package]
name = "opcode-registry"
version = "0.1.0"
edition = "2024"
description = "⚡ opcode - Zero-copy binary serialization with compile-time guarantees 🎩"
license = "MIT"
repository = "https://github.com/boxblocks/opcode"

[dependencies]
